## Vectorization 

In [1]:
import numpy as np

In [2]:
a =  np.array([1,2,3,4])
b =  np.array([2,34,6,7])
print(a)

np.dot(a,b)

[1 2 3 4]


116

In [3]:
n = 3
np.exp(np.zeros((n,1)))
#np.zeros


array([[1.],
       [1.],
       [1.]])

In [4]:
a = np.arange(15).reshape(3,5)

In [5]:
a.size


15

In [6]:
a.ndim

2

In [7]:
a.dtype.name

'int32'

In [8]:
np.zeros((1,4))

array([[0., 0., 0., 0.]])

In [9]:
cal_ = np.array([[56,0,4.4,68],[1.2,104,52,8],[1.8,135,99,0.9]])

In [10]:
call_total = cal_.sum(axis= 0)
call_total

array([ 59. , 239. , 155.4,  76.9])

In [11]:
percentage = 100 * cal_ / call_total.reshape(1,4)

In [12]:
percentage

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [13]:
aa = np.random.rand(5)
print(aa[1])
print(aa[[1]])
print("aa transpose ",aa.T)
print("aa ",aa) ## these are rank 1 arrays
aa.shape

## rank 1 arrays are cause problems 
## so reshape
aa.reshape(5,1)

0.9438520011426543
[0.943852]
aa transpose  [0.62531803 0.943852   0.72400217 0.93758158 0.32157256]
aa  [0.62531803 0.943852   0.72400217 0.93758158 0.32157256]


array([[0.62531803],
       [0.943852  ],
       [0.72400217],
       [0.93758158],
       [0.32157256]])

In [14]:
aa_ = np.random.rand(5,1) ## use this notation (5,1 )

print("aa_ transpose ", aa_.T) ## column vector
print("aa_ ", aa_)
aa_.shape

aa_ transpose  [[0.47452309 0.67353066 0.37613143 0.93691854 0.70195747]]
aa_  [[0.47452309]
 [0.67353066]
 [0.37613143]
 [0.93691854]
 [0.70195747]]


(5, 1)

In [15]:
np.array([1,2,3,3])

np.array([[1,1,1,1],[1232,33,44,44]])

np.array([(1,1,1,1),(1232,33,44,44)])



try:
    np.array(1,2,3) ## gives an error
except ValueError : 
    print("A vector cannot be written like that")
    


A vector cannot be written like that


In [16]:
one_ = np.ones((2,3,4))
one_.ndim
## 3 dimension array

np.empty((2,3))

np.arange(10,30,5) ## array of numbers with 5 spacing

np.arange(6)


array([0, 1, 2, 3, 4, 5])

In [17]:
np.arange(10).reshape(5,2)

try:
    np.arange(10).reshape(5,3)
except ValueError:
    print("the # values should be ten not fifteen.")

the # values should be ten not fifteen.


In [18]:
floor_ = np.floor((10*np.random.random((3,4))))
print("floor command result ", floor_)
floor_.shape

ravel_ = floor_.ravel()  ## faltten an array
ravel_.shape
print("RAVEL outputs flattened version of the rows. ",ravel_)

floor command result  [[0. 6. 4. 4.]
 [1. 5. 6. 4.]
 [9. 7. 7. 5.]]
RAVEL outputs flattened version of the rows.  [0. 6. 4. 4. 1. 5. 6. 4. 9. 7. 7. 5.]


In [19]:
transpose_ = np.arange(12).reshape(6,2)
print("a matrix \n", transpose_, "\n")
T_transpose = transpose_.T
print("its transpose \n", T_transpose)

a matrix 
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]] 

its transpose 
 [[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]


In [20]:
resize_ = np.arange(12).reshape(4,3)

print(resize_)
print(resize_.reshape(6,2)) ## to assign to a new variable

print(resize_.resize((6,2)))  ## modifies the array permanantly
resize_


resize_.reshape(3,-1) ## when -1 the other dimention is automatically calculated. 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
None


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
a = np.arange(12).reshape(3,4)
print("my a matric \n", a, "\n")

##
print("Multiplication of matrix \n",10*a, "\n")

b = np.arange(12).reshape(3,4)
print("b \n",b, "\n")
print("matrix multiplication \n",a*b, "\n") ## matrix multiplication
b = np.arange(4).reshape(4,1)
print("Broadcasting \n",a@b, "\n") ## matrix multiplication

b = np.arange(12).reshape(4,3)
a@b



my a matric 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

Multiplication of matrix 
 [[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]] 

b 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

matrix multiplication 
 [[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]] 

Broadcasting 
 [[14]
 [38]
 [62]] 



array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

__Next Steps__ <br>
[Broadcasting NUMPY](https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html) <br>
[Quick Tutorial NUMPY](https://docs.scipy.org/doc/numpy/user/quickstart.html)
